use bup::BupError;

fn main() -> Result<(), BupError> {
    Ok(())
}
